/**
 * Mission Schema v0.1 — Candidate
 *
 * Source: docs/philos-universal-data-model-v0.md §2.2
 * Grade:  Candidate — structure designed; not validated on real mission records.
 *         Do not promote to Frozen until at least one real Mission record has been
 *         created, read, and found complete.
 *
 * The Mission is the root entity of the PUDM chain:
 *   Mission → Gap → Value → Capability → Provider
 *
 * All subsystems (OPM, Marketplace, World, Agents) interact with Mission
 * through MissionRepository, not through this file directly.
 */

// ─── Shared primitives ───────────────────────────────────────────────────────

export type EvidenceGrade =
  | "Frozen"
  | "Candidate"
  | "Placeholder"
  | "Not established";

export type SignalType = "Intent" | "Behavior" | "Outcomes";

export type MissionStatus = "active" | "completed" | "abandoned" | "paused";

export type MissionHorizon = "immediate" | "medium" | "long";

export type ActorType = "Person" | "Organization" | "Community";

// ─── Sub-structures (4-layer PUDM node model) ────────────────────────────────

/** Layer 1 + base: Identity — what this Mission is. */
export interface MissionIdentity {
  id: string;
  type: "Mission";
  createdAt: string;  // ISO 8601
  updatedAt: string;  // ISO 8601
  evidenceGrade: EvidenceGrade;
}

/** Layer 2a: State — current lifecycle position. */
export interface MissionState {
  status: MissionStatus;
  horizon: MissionHorizon;
}

/** Layer 2b: Context — who is running this Mission and why. */
export interface MissionContext {
  actor: {
    id: string;
    type: ActorType;
    displayName: string;
  };
  statement: string;   // what the actor is trying to achieve
  domain: string | null;
}

/** Layer 2c: Constraints — what limits or assumptions shape this Mission. */
export interface MissionConstraints {
  constraints: string[];
  assumptions: string[];
}

/** Reference to a Gap node. Gaps are resolved in the Gap domain (not yet built). */
export interface GapRef {
  gapId: string;
  description: string;
  status: "open" | "closed" | "deferred";
}

/** Reference to a Value node (one of the 12 Candidate values). */
export interface ValueRef {
  valueId: string;
  label: string;
  grade: EvidenceGrade;
}

/** Reference to a Capability Domain node. */
export interface CapabilityRef {
  capabilityId: string;
  domain: string;
}

/** Reference to a Provider node. */
export interface ProviderRef {
  providerId: string;
  name: string;
}

/** Single evidence signal attached to this Mission. */
export interface EvidenceRecord {
  signal: SignalType;
  source: string | null;
  observedAt: string | null;  // ISO 8601
  note: string;
}

/** Layer 4a: Timeline — when things happened or are expected. */
export interface MissionTimeline {
  startedAt: string | null;   // ISO 8601
  targetAt: string | null;
  completedAt: string | null;
}

/** Layer 3 (Relations): other Missions this one connects to. */
export interface MissionRelations {
  relatedMissions: string[];  // MissionId[]
}

// ─── Full Mission node ────────────────────────────────────────────────────────

export interface Mission extends MissionIdentity {
  state: MissionState;
  context: MissionContext;
  constraints: MissionConstraints;
  gaps: GapRef[];
  requiredValues: ValueRef[];
  capabilities: CapabilityRef[];
  providers: ProviderRef[];
  evidence: EvidenceRecord[];
  timeline: MissionTimeline;
  relations: MissionRelations;
}

// ─── Input types (used by MissionRepository) ─────────────────────────────────

/** Everything needed to create a new Mission. id, type, createdAt, updatedAt are
 *  generated by the repository; evidenceGrade defaults to "Candidate". */
export type CreateMissionInput = Omit<
  Mission,
  "id" | "type" | "createdAt" | "updatedAt"
> & {
  evidenceGrade?: EvidenceGrade;
};

/** Partial update — only supply the fields that change.
 *  id, type, and createdAt are immutable after creation. */
export type UpdateMissionInput = Partial<
  Omit<Mission, "id" | "type" | "createdAt">
>;
