/**
 * Capability Schema v0.1 — Candidate
 *
 * Source: docs/philos-universal-data-model-v0.md §2.3
 * Grade:  Candidate — structure designed; not validated against real
 *         Capability records or Provider mappings.
 *         Do not promote to Frozen until capabilities have been confirmed
 *         against real Gap closures and Provider evidence.
 *
 * Capability is the fourth node in the PUDM chain:
 *   Mission → Gap → Value → Capability → Provider
 *
 * A Capability is a domain of ability that can address one or more Values.
 * It is the bridge between what a Gap requires (Values) and who can deliver
 * it (Providers). Capability owns its domain label and maturity rating.
 *
 * Design rule: Capability owns its context and provider pointers.
 * It does NOT own Value links, Gap data, Mission data, or Provider data.
 * Value → Capability links are owned by ValueCapabilityRelation.
 * Back-pointers to Missions and Gaps are resolved by querying their
 * repositories — they are never stored on the Capability node.
 */

import type { EvidenceGrade, SignalType, ProviderRef } from "../types";
export type { EvidenceGrade, SignalType, ProviderRef };

// ─── Sub-structures (4-layer PUDM node model) ────────────────────────────────

/** Layer 1 + base: Identity — what this Capability is. */
export interface CapabilityIdentity {
  id: string;
  type: "Capability";
  createdAt: string;   // ISO 8601
  updatedAt: string;
  evidenceGrade: EvidenceGrade;
}

/**
 * How developed this capability is in practice.
 * emerging  — the domain exists but delivery is inconsistent or nascent.
 * established — delivery is reliable and practitioners exist.
 * proven    — capability has been demonstrated with Outcomes-grade evidence.
 */
export type CapabilityMaturity = "emerging" | "established" | "proven";

/**
 * Layer 2: Context — the human meaning of this Capability.
 *
 * label is the canonical display name.
 * description explains what this capability does in the Philos context.
 * domain is the primary operational sphere (Finance, Design, etc.).
 * maturity is the current development stage of this capability.
 */
export interface CapabilityContext {
  label: string;
  description: string;
  domain: string | null;
  maturity: CapabilityMaturity | null;
}

/**
 * Single evidence signal scoped to the Capability definition itself.
 *
 * TEMPORARY — v0.1 only.
 * Per PUDM §4.3, evidence belongs on relation instances, not on nodes.
 * This field represents only "evidence that this Capability is correctly
 * defined and real" — not relation evidence (Value → Capability, etc.).
 * Will migrate to relation-level evidence in a future revision.
 */
export interface CapabilityEvidenceRecord {
  signal: SignalType;
  source: string | null;
  observedAt: string | null;  // ISO 8601
  note: string;
}

// ─── Full Capability node ─────────────────────────────────────────────────────

/**
 * Capability owns:
 *   - Its own label, description, domain, maturity, and evidenceGrade.
 *   - Pure reference pointers to Provider nodes (empty until Provider built).
 *   - Temporary self-scoped evidence (see CapabilityEvidenceRecord above).
 *
 * Capability does NOT own:
 *   - Value links (owned by ValueCapabilityRelation — query that repository).
 *   - Gap descriptions or lifecycle (owned by Gap node).
 *   - Mission statements or actor (owned by Mission node).
 *   - Provider details (owned by Provider node).
 *   - Back-pointers to Missions or Gaps (resolved via their repositories).
 */
export interface Capability extends CapabilityIdentity {
  context: CapabilityContext;
  providers: ProviderRef[];       // empty until Provider entity is built
  evidence: CapabilityEvidenceRecord[];
}

// ─── Convenience re-exports ───────────────────────────────────────────────────

export type { CapabilityRef } from "../types";

// ─── Input types (used by CapabilityRepository) ───────────────────────────────

/** Everything needed to create a new Capability. id, type, createdAt, updatedAt
 *  are generated by the repository; evidenceGrade defaults to "Candidate". */
export type CreateCapabilityInput = Omit<
  Capability,
  "id" | "type" | "createdAt" | "updatedAt"
> & {
  evidenceGrade?: EvidenceGrade;
};

/** Partial update — only supply the fields that change.
 *  id, type, and createdAt are immutable after creation. */
export type UpdateCapabilityInput = Partial<Omit<Capability, "id" | "type" | "createdAt">>;
