/**
 * Gap Schema v0.1 — Candidate
 *
 * Source: docs/philos-universal-data-model-v0.md §2.2
 * Grade:  Candidate — structure designed; not validated on real Gap records.
 *         Do not promote to Frozen until at least one real Gap record has been
 *         created and found complete against a real Mission.
 *
 * Gap is the second node in the PUDM chain:
 *   Mission → Gap → Value → Capability → Provider
 *
 * A Gap represents the distance between a Mission's current state and what
 * it needs to succeed. Gap owns its own description and lifecycle.
 * Mission holds only a GapRef { gapId } pointer.
 *
 * Design rule: Gap owns its description, status, and required values.
 * It does NOT own Mission data, Value data, Capability data, or Provider data.
 */

import type { EvidenceGrade, SignalType, ValueRef } from "../types";
export type { EvidenceGrade, SignalType };

// ─── Gap-specific types ───────────────────────────────────────────────────────

export type GapStatus = "open" | "closed" | "deferred";

export type GapSeverity = "critical" | "significant" | "moderate" | "minor";

// ─── Sub-structures (4-layer PUDM node model) ────────────────────────────────

/** Layer 1 + base: Identity — what this Gap is. */
export interface GapIdentity {
  id: string;
  type: "Gap";
  createdAt: string;  // ISO 8601
  updatedAt: string;
  evidenceGrade: EvidenceGrade;
}

/** Layer 2a: State — current lifecycle position. */
export interface GapState {
  status: GapStatus;
  /** Qualitative severity — Placeholder until measurement protocol exists. */
  severity: GapSeverity | null;
}

/**
 * Layer 2b: Context — what the gap is and which Mission originated it.
 *
 * missionId is the pointer back to the Mission that contains this Gap.
 * Mission statement and actor are owned by the Mission node.
 */
export interface GapContext {
  missionId: string;
  description: string;
  domain: string | null;
}

/**
 * Single evidence signal scoped to the Gap itself.
 *
 * TEMPORARY — v0.1 only.
 * Per PUDM §4.3, evidence belongs on relation instances, not on nodes.
 * This field represents only "evidence that this Gap is real and accurately
 * described" — not relation evidence (Gap → Value, etc.).
 * Will migrate to relation-level evidence in a future revision.
 */
export interface GapEvidenceRecord {
  signal: SignalType;
  source: string | null;
  observedAt: string | null;  // ISO 8601
  note: string;
}

/** Layer 4: Dynamics — when the gap opened and closed. */
export interface GapTimeline {
  openedAt: string | null;    // ISO 8601
  closedAt: string | null;
  deferredUntil: string | null;
}

// ─── Full Gap node ────────────────────────────────────────────────────────────

/**
 * Gap owns:
 *   - Its own description, status, severity, and timeline.
 *   - The missionId it was derived from (pointer only).
 *   - Pure reference pointers to required Value nodes.
 *   - Temporary self-scoped evidence (see GapEvidenceRecord above).
 *
 * Gap does NOT own:
 *   - Mission statement or actor (owned by Mission node).
 *   - Value labels or evidence grades (owned by Value node).
 *   - Capability or Provider data (resolved by traversing the chain).
 */
export interface Gap extends GapIdentity {
  state: GapState;
  context: GapContext;
  requiredValues: ValueRef[];
  evidence: GapEvidenceRecord[];
  timeline: GapTimeline;
}

// ─── Input types (used by GapRepository) ─────────────────────────────────────

/** Everything needed to create a new Gap. id, type, createdAt, updatedAt are
 *  generated by the repository; evidenceGrade defaults to "Candidate". */
export type CreateGapInput = Omit<
  Gap,
  "id" | "type" | "createdAt" | "updatedAt"
> & {
  evidenceGrade?: EvidenceGrade;
};

/** Partial update — only supply the fields that change.
 *  id, type, and createdAt are immutable after creation. */
export type UpdateGapInput = Partial<Omit<Gap, "id" | "type" | "createdAt">>;
