/**
 * Provider Schema v0.1 — Candidate
 *
 * Source: docs/philos-universal-data-model-v0.md §2.4
 * Grade:  Candidate — structure designed; not validated against real
 *         Provider records or confirmed Capability delivery evidence.
 *         Do not promote to Frozen until providers have been confirmed
 *         against real mission outcomes or Behavior-grade evidence.
 *
 * Provider is the fifth node in the PUDM chain:
 *   Mission → Gap → Value → Capability → Provider
 *
 * A Provider is an actor — organization, individual, platform, or program —
 * that can deliver one or more Capabilities. It is the bridge between what
 * a Capability requires and who concretely executes it.
 *
 * Design rule: Provider owns its identity, type, and context.
 * It does NOT own Capability links, Value data, Gap data, or Mission data.
 * Provider → Capability links are owned by ProviderCapabilityRelation.
 * Back-pointers to Capabilities, Values, or Missions are resolved by
 * querying their repositories — they are never stored on the Provider node.
 */

import type { EvidenceGrade, SignalType } from "../types";
export type { EvidenceGrade, SignalType };

// ─── Sub-structures ───────────────────────────────────────────────────────────

/** What kind of actor the Provider is. */
export type ProviderType = "organization" | "individual" | "platform" | "program";

/** Layer 1 + base: Identity — what this Provider is. */
export interface ProviderIdentity {
  id: string;
  type: "Provider";
  createdAt: string;   // ISO 8601
  updatedAt: string;
  evidenceGrade: EvidenceGrade;
}

/**
 * Layer 2: Context — the human meaning of this Provider.
 *
 * label         is the canonical display name.
 * description   explains what this provider does and how it relates to Philos.
 * domain        is the primary operational sphere (Finance, Operations, etc.).
 * providerType  classifies the actor kind.
 * website       is an optional public URL for reference only.
 */
export interface ProviderContext {
  label: string;
  description: string;
  domain: string | null;
  providerType: ProviderType;
  website: string | null;
}

/**
 * Single evidence signal scoped to the Provider definition itself.
 *
 * TEMPORARY — v0.1 only.
 * Per PUDM §4.3, evidence belongs on relation instances, not on nodes.
 * This field represents only "evidence that this Provider is correctly
 * defined and real" — not relation evidence (Provider → Capability, etc.).
 * Will migrate to relation-level evidence in a future revision.
 */
export interface ProviderEvidenceRecord {
  signal: SignalType;
  source: string | null;
  observedAt: string | null;  // ISO 8601
  note: string;
}

// ─── Full Provider node ───────────────────────────────────────────────────────

/**
 * Provider owns:
 *   - Its own label, description, domain, providerType, and evidenceGrade.
 *   - Temporary self-scoped evidence (see ProviderEvidenceRecord above).
 *
 * Provider does NOT own:
 *   - Capability links (owned by ProviderCapabilityRelation — query that repository).
 *   - Value descriptions or lifecycle (owned by Value node).
 *   - Gap descriptions or lifecycle (owned by Gap node).
 *   - Mission statements or actor (owned by Mission node).
 *   - Back-pointers to Capabilities, Values, Gaps, or Missions.
 */
export interface Provider extends ProviderIdentity {
  context: ProviderContext;
  evidence: ProviderEvidenceRecord[];
}

// ─── Convenience re-exports ───────────────────────────────────────────────────

export type { ProviderRef } from "../types";

// ─── Input types (used by ProviderRepository) ─────────────────────────────────

/** Everything needed to create a new Provider. id, type, createdAt, updatedAt
 *  are generated by the repository; evidenceGrade defaults to "Candidate". */
export type CreateProviderInput = Omit<
  Provider,
  "id" | "type" | "createdAt" | "updatedAt"
> & {
  evidenceGrade?: EvidenceGrade;
};

/** Partial update — only supply the fields that change.
 *  id, type, and createdAt are immutable after creation. */
export type UpdateProviderInput = Partial<Omit<Provider, "id" | "type" | "createdAt">>;
