/**
 * Value Schema v0.1 — Candidate
 *
 * Source: docs/philos-universal-data-model-v0.md §2.2
 * Grade:  Candidate — structure designed; not validated on real Value records.
 *         Do not promote to Frozen until the 12 canonical values have been
 *         created and confirmed complete against real Missions and Gaps.
 *
 * Value is the third node in the PUDM chain:
 *   Mission → Gap → Value → Capability → Provider
 *
 * A Value represents one of the universal goods that a Gap requires in order
 * to be closed. The 12 Candidate values are defined in /world.
 * Value owns its own label, description, and domain.
 * Gap holds only a ValueRef { valueId } pointer.
 *
 * Design rule: Value owns its description and context.
 * It does NOT own Gap data, Mission data, Capability data, or Provider data.
 * Back-pointers to Missions and Gaps are resolved by querying their
 * repositories — they are never stored on the Value node.
 */

import type { EvidenceGrade, SignalType } from "../types";
export type { EvidenceGrade, SignalType };

// ─── Sub-structures (4-layer PUDM node model) ────────────────────────────────

/** Layer 1 + base: Identity — what this Value is. */
export interface ValueIdentity {
  id: string;
  type: "Value";
  createdAt: string;   // ISO 8601
  updatedAt: string;
  evidenceGrade: EvidenceGrade;
}

/**
 * Layer 2: Context — the human meaning of this Value.
 *
 * label is the canonical display name (e.g. "Capital", "Trust").
 * description explains what the value means in the Philos context —
 *   not a dictionary definition, but how it functions in the PUDM chain.
 * domain is the primary sphere where this value operates (Finance, Social, etc.).
 */
export interface ValueContext {
  label: string;
  description: string;
  domain: string | null;
}

/**
 * Pure pointer to a Capability node that can help fulfill this Value.
 * Capability label and evidence are owned by the Capability node.
 * Resolve from CapabilityRepository when display data is needed.
 */
export interface CapabilityRef {
  capabilityId: string;
}

/**
 * Single evidence signal scoped to the Value definition itself.
 *
 * TEMPORARY — v0.1 only.
 * Per PUDM §4.3, evidence belongs on relation instances, not on nodes.
 * This field represents only "evidence that this Value is correctly defined
 * and real" — not relation evidence (Gap → Value, etc.).
 * Will migrate to relation-level evidence in a future revision.
 */
export interface ValueEvidenceRecord {
  signal: SignalType;
  source: string | null;
  observedAt: string | null;  // ISO 8601
  note: string;
}

// ─── Full Value node ──────────────────────────────────────────────────────────

/**
 * Value owns:
 *   - Its own label, description, domain, and evidenceGrade.
 *   - Pure reference pointers to Capability nodes that fulfill it.
 *   - Temporary self-scoped evidence (see ValueEvidenceRecord above).
 *
 * Value does NOT own:
 *   - Gap descriptions or lifecycle (owned by Gap node).
 *   - Mission statements or actor (owned by Mission node).
 *   - Capability details (owned by Capability node).
 *   - Provider data (resolved by traversing the chain).
 *   - Back-pointers to Missions or Gaps (resolved via their repositories).
 */
export interface Value extends ValueIdentity {
  context: ValueContext;
  capabilities: CapabilityRef[];
  evidence: ValueEvidenceRecord[];
}

// ─── Input types (used by ValueRepository) ───────────────────────────────────

/** Everything needed to create a new Value. id, type, createdAt, updatedAt
 *  are generated by the repository; evidenceGrade defaults to "Candidate". */
export type CreateValueInput = Omit<
  Value,
  "id" | "type" | "createdAt" | "updatedAt"
> & {
  evidenceGrade?: EvidenceGrade;
};

/** Partial update — only supply the fields that change.
 *  id, type, and createdAt are immutable after creation. */
export type UpdateValueInput = Partial<Omit<Value, "id" | "type" | "createdAt">>;
